let nome = "feleppe almeida"
console.log("nome antes: " + nome)

nome = "jackeline almeida"
console.log("nome depois: " + nome)

nome = "maria almeida"
console.log("nome no final: " + nome)


const nomeCompleto = "luiz silva"

console.log("Nome agora: " + nomeCompleto)

nomeCompleto = "maria eduarda silva"

console.log("Nome depois: " + nomeCompleto)

nomeCompleto = "sextou"

console.log("sextou")




